version: '3'
services:
  web:
    build: .
    command: python /code/blogDjango/manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/code
      - ./media:/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=blogDjango.settings.prod
    networks:
      - my_network

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/static:ro
      - ./media:/media
    depends_on:
      - web
    networks:
      - my_network

networks:
  my_network:
