# Generated by Django 4.2.3 on 2023-07-31 06:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TutorialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_category', models.CharField(max_length=255)),
                ('category_summary', models.TextField()),
                ('category_slug', models.SlugField()),
                ('category_img', models.ImageField(blank=True, upload_to='media/category_img', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'svg'])])),
            ],
        ),
        migrations.CreateModel(
            name='TutorialSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_series', models.CharField(max_length=255)),
                ('series_summary', models.TextField()),
                ('series_slug', models.SlugField()),
                ('series_img', models.ImageField(blank=True, upload_to='media/series_img')),
                ('tutorial_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tutorialcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=255, unique=True)),
                ('tutorial_description', models.CharField(max_length=160)),
                ('tutorial_content', models.TextField()),
                ('tutorial_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('tutorial_slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='PB', max_length=2)),
                ('tutorial_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tutorialseries')),
            ],
        ),
    ]
