# Generated by Django 4.2.3 on 2023-07-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialseries',
            name='series_img',
            field=models.ImageField(blank=True, upload_to='../static/media/series_img'),
        ),
    ]
